### ISSUE TITLE
Implement TanStack router

### ISSUE THREAD

**Issue by gregmulvaney** [gregmulvaney/yop#5]
Implement TanStack router and establish a basic configuration.

**Comment by phillip-hirsch** [comment]
Docs: https://tanstack.com/router/latest/docs/framework/react/installation

**Comment by gregmulvaney** [comment]
Completed in [PR#7](https://github.com/gregmulvaney/yop/pull/7)

**Comment by gregmulvaney** [comment]
Completed in [PR#7](https://github.com/gregmulvaney/yop/pull/7)

**Comment by gregmulvaney** [comment]
Completed in #7
